"""Screen gentler one-cycle probes using actual mechanics traces and detector floor.

This early-Phase-2 co-design sensitivity joins two already-separated facts: the
bounded mechanics traces and the sensor-model-derived synchronous threshold.  It
does not freeze configuration or generate confirmatory data.  A candidate advances
only when every fault/source differential clears the detector threshold with a
declared margin and every simulated scenario stays inside the development safety
envelope.
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import asdict, replace
from pathlib import Path
from typing import Any

import numpy as np

from run_bounded_burst_sensitivity import (
    build_candidates,
    load_budget,
    plain,
    signature_screen,
)
from run_feasibility_spike import SimulationResult, simulate_case
from utils.synchronous import harmonic_amplitude


def parse_args() -> argparse.Namespace:
    """Parse portable mechanics/detector co-design arguments."""

    parser = argparse.ArgumentParser(
        description="Screen low-amplitude one-cycle probes on actual MuJoCo gauge traces."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/synchronous_safe_probe"),
        help="Project-relative output directory.",
    )
    parser.add_argument(
        "--detector-summary",
        type=Path,
        default=Path("results/synchronous_detection_floor/summary.json"),
        help="Detector-floor JSON generated by analyze_synchronous_detection_floor.py.",
    )
    parser.add_argument(
        "--task-torque-scales", type=float, nargs="+", default=[0.4, 0.5]
    )
    parser.add_argument("--peak-loads-n", type=float, nargs="+", default=[0.05, 0.1, 0.15])
    parser.add_argument("--minimum-detector-margin", type=float, default=2.0)
    parser.add_argument("--fault-onset-s", type=float, default=1.0)
    parser.add_argument("--frequency-hz", type=float, default=0.8)
    parser.add_argument("--ramp-period-fraction", type=float, default=0.125)
    parser.add_argument("--settle-s", type=float, default=0.25)
    parser.add_argument("--point-count", type=int, default=17)
    parser.add_argument("--simulation-timestep-s", type=float, default=1.0e-4)
    return parser.parse_args()


def load_detector_contract(path: Path, frequency_hz: float) -> dict[str, float]:
    """Load the development synchronous threshold and its exact window contract."""

    with Path(path).open("r", encoding="utf-8") as handle:
        summary = json.load(handle)
    config = summary["config"]
    null = summary["noise_only_null"]
    if not np.isclose(float(config["diagnostic_hz"]), frequency_hz):
        raise ValueError("detector summary frequency does not match the probe")
    if not np.isclose(float(config["f_ctrl_hz"]), 500.0):
        raise ValueError("detector summary must use the selected 500 Hz control grid")
    window = int(config["window_samples"])
    if window < int(np.ceil(config["f_ctrl_hz"] / frequency_hz)):
        raise ValueError("detector window must cover at least one complete probe cycle")
    threshold = float(null["detect_threshold_microstrain"])
    if not np.isfinite(threshold) or threshold <= 0.0:
        raise ValueError("detector threshold must be finite and positive")
    return {
        "frequency_hz": float(config["diagnostic_hz"]),
        "f_ctrl_hz": float(config["f_ctrl_hz"]),
        "window_samples": window,
        "detect_threshold_microstrain": threshold,
        "realizations": int(config["realizations"]),
    }


def actual_harmonic_signatures(
    cases: dict[str, SimulationResult],
    *,
    onset_s: float,
    window_samples: int,
    frequency_hz: float,
) -> dict[str, dict[str, Any]]:
    """Measure known-frequency amplitudes on actual fault-minus-healthy gauge traces."""

    healthy = cases["healthy"]
    post = np.flatnonzero(healthy.time_s >= onset_s - 1.0e-12)
    if post.size < window_samples:
        raise ValueError("mechanics trace is shorter than the detector window")
    selected = post[:window_samples]
    time_s = healthy.time_s[selected]
    if time_s[-1] - time_s[0] + healthy.time_s[1] - healthy.time_s[0] < 1.0 / frequency_hz:
        raise ValueError("selected mechanics window does not contain a complete probe cycle")

    comparisons = {
        "structural_minus_healthy": ("structural", "healthy"),
        "actuator_minus_healthy": ("actuator", "healthy"),
        "structural_minus_actuator": ("structural", "actuator"),
    }
    output: dict[str, dict[str, Any]] = {}
    for name, (left, right) in comparisons.items():
        delta = (
            cases[left].gauge_microstrain[selected]
            - cases[right].gauge_microstrain[selected]
        )
        amplitudes = np.asarray(
            [
                harmonic_amplitude(
                    delta[:, channel], np.ones(window_samples, dtype=bool), time_s, frequency_hz
                )
                for channel in range(delta.shape[1])
            ]
        )
        best_channel = int(np.argmax(amplitudes))
        output[name] = {
            "per_gauge_amplitude_microstrain": amplitudes,
            "max_amplitude_microstrain": float(amplitudes[best_channel]),
            "max_gauge_index": best_channel,
        }
    return output


def build_probe_candidates(args: argparse.Namespace) -> list[tuple[str, Any]]:
    """Build the deterministic low-task/low-load one-cycle candidate grid."""

    if not args.task_torque_scales or not args.peak_loads_n:
        raise ValueError("task-torque and peak-load candidate lists cannot be empty")
    if any(not np.isfinite(value) or value < 0.0 for value in args.task_torque_scales):
        raise ValueError("task torque scales must be finite and non-negative")
    if any(not np.isfinite(value) or value <= 0.0 for value in args.peak_loads_n):
        raise ValueError("peak loads must be finite and positive")
    if not np.isfinite(args.minimum_detector_margin) or args.minimum_detector_margin <= 1.0:
        raise ValueError("minimum detector margin must be finite and greater than one")

    candidates: list[tuple[str, Any]] = []
    for task_scale in sorted(set(args.task_torque_scales)):
        for peak_load in sorted(set(args.peak_loads_n)):
            bounded = build_candidates(
                onset_s=args.fault_onset_s,
                peak_load_n=peak_load,
                frequency_hz=args.frequency_hz,
                cycles=[1],
                ramp_period_fraction=args.ramp_period_fraction,
                settle_s=args.settle_s,
                include_controls=False,
            )[0]
            config = replace(bounded.config, task_torque_scale=task_scale)
            name = f"task_{task_scale:.3f}_probe_{peak_load:.3f}N"
            candidates.append((name, replace(bounded, name=name, config=config)))
    return candidates


def write_csv(path: Path, results: list[dict[str, Any]]) -> None:
    """Write the decision-facing candidate comparison."""

    fields = [
        "name",
        "task_torque_scale",
        "peak_load_n",
        "structural_harmonic_microstrain",
        "actuator_harmonic_microstrain",
        "separation_harmonic_microstrain",
        "minimum_detector_margin",
        "worst_peak_abs_joint_angle_rad",
        "worst_peak_abs_joint_speed_rad_s",
        "safety_screen_pass",
        "detector_screen_pass",
        "advance_to_pilot_sweep",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for result in results:
            signatures = result["harmonic_signatures"]
            screen = result["screen"]
            writer.writerow(
                {
                    "name": result["name"],
                    "task_torque_scale": result["config"]["task_torque_scale"],
                    "peak_load_n": result["config"]["diagnostic_tip_load_peak_n"],
                    "structural_harmonic_microstrain": signatures[
                        "structural_minus_healthy"
                    ]["max_amplitude_microstrain"],
                    "actuator_harmonic_microstrain": signatures["actuator_minus_healthy"][
                        "max_amplitude_microstrain"
                    ],
                    "separation_harmonic_microstrain": signatures[
                        "structural_minus_actuator"
                    ]["max_amplitude_microstrain"],
                    "minimum_detector_margin": result["minimum_detector_margin"],
                    "worst_peak_abs_joint_angle_rad": screen[
                        "worst_peak_abs_joint_angle_rad"
                    ],
                    "worst_peak_abs_joint_speed_rad_s": screen[
                        "worst_peak_abs_joint_speed_rad_s"
                    ],
                    "safety_screen_pass": screen["safety_screen_pass"],
                    "detector_screen_pass": result["detector_screen_pass"],
                    "advance_to_pilot_sweep": result["advance_to_pilot_sweep"],
                }
            )


def write_report(path: Path, summary: dict[str, Any]) -> None:
    """Write a concise human-readable co-design decision record."""

    detector = summary["detector_contract"]
    lines = [
        "# Synchronous Safe-Probe Co-Design Screen",
        "",
        f"**Decision: {summary['recommendation']['decision']}.** "
        f"{summary['recommendation']['reason']}",
        "",
        "Development sensitivity only: no config is frozen and no trace is confirmatory. "
        "Unlike the detector-floor surrogate, this screen measures the synchronous feature "
        "on the actual four-gauge MuJoCo fault-minus-healthy histories and checks safety "
        "across healthy, structural, actuator, and encoder cases.",
        "",
        f"Detector contract: W={detector['window_samples']} at 500 Hz, "
        f"f_d={detector['frequency_hz']:.1f} Hz, development threshold "
        f"{detector['detect_threshold_microstrain']:.3f} microstrain, required margin "
        f"{summary['minimum_required_margin']:.1f}x.",
        "",
        "| Candidate | Structural | Actuator | Separation | Min margin | Worst angle | Worst speed | Safety | Detector | Advance |",
        "|---|---:|---:|---:|---:|---:|---:|---|---|---|",
    ]
    for result in summary["results"]:
        signatures = result["harmonic_signatures"]
        screen = result["screen"]
        lines.append(
            f"| {result['name']} | "
            f"{signatures['structural_minus_healthy']['max_amplitude_microstrain']:.3f} | "
            f"{signatures['actuator_minus_healthy']['max_amplitude_microstrain']:.3f} | "
            f"{signatures['structural_minus_actuator']['max_amplitude_microstrain']:.3f} | "
            f"{result['minimum_detector_margin']:.2f}x | "
            f"{screen['worst_peak_abs_joint_angle_rad']:.2f} rad | "
            f"{screen['worst_peak_abs_joint_speed_rad_s']:.2f} rad/s | "
            f"{'PASS' if screen['safety_screen_pass'] else 'BLOCK'} | "
            f"{'PASS' if result['detector_screen_pass'] else 'BLOCK'} | "
            f"{'YES' if result['advance_to_pilot_sweep'] else 'NO'} |"
        )
    lines.extend(
        [
            "",
            "## Boundaries",
            "",
            "- This is a mechanics/detector development screen, not fault attribution and not "
            "evidence that S beats C1.",
            "- The threshold comes from the current modeled sensor path and must be frozen on "
            "validation data later; nonlinear or probe-band thermal interference remains open.",
            "- The selected row advances only to the pilot sweep. Contact is disabled in this "
            "plant, so optional-contact cases still require endpoint-contact extraction.",
            "- The legacy 10-microstrain per-sample gate remains preserved as the mechanics-"
            "selection record; this screen does not rewrite it.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(args: argparse.Namespace) -> dict[str, Any]:
    """Run the candidate grid, write artifacts, and return its decision summary."""

    detector = load_detector_contract(args.detector_summary, args.frequency_hz)
    candidates = build_probe_candidates(args)
    results: list[dict[str, Any]] = []
    for name, candidate in candidates:
        print(f"Running {name} ...", flush=True)
        cases = {
            scenario: simulate_case(
                candidate.config, args.point_count, args.simulation_timestep_s, scenario
            )
            for scenario in ("healthy", "structural", "actuator", "encoder")
        }
        screen = signature_screen(cases, candidate.config, candidate.analysis_duration_s)
        signatures = actual_harmonic_signatures(
            cases,
            onset_s=args.fault_onset_s,
            window_samples=detector["window_samples"],
            frequency_hz=args.frequency_hz,
        )
        threshold = detector["detect_threshold_microstrain"]
        margins = [
            item["max_amplitude_microstrain"] / threshold for item in signatures.values()
        ]
        minimum_margin = float(min(margins))
        detector_pass = minimum_margin >= args.minimum_detector_margin
        advance = bool(screen["safety_screen_pass"] and detector_pass)
        results.append(
            plain(
                {
                    "name": name,
                    "config": asdict(candidate.config),
                    "load_budget": load_budget(
                        candidate.config, args.simulation_timestep_s
                    ),
                    "screen": screen,
                    "harmonic_signatures": signatures,
                    "minimum_detector_margin": minimum_margin,
                    "detector_screen_pass": detector_pass,
                    "advance_to_pilot_sweep": advance,
                }
            )
        )

    eligible = [result for result in results if result["advance_to_pilot_sweep"]]
    eligible.sort(
        key=lambda result: (
            result["config"]["diagnostic_tip_load_peak_n"],
            result["config"]["task_torque_scale"],
        )
    )
    if eligible:
        selected = eligible[0]
        recommendation = {
            "decision": f"ADVANCE {selected['name']} TO PILOT SWEEP",
            "candidate": selected["name"],
            "reason": (
                "It is the smallest screened force/task pair that clears the actual-trace "
                "detector margin and all four-scenario development safety checks."
            ),
        }
    else:
        recommendation = {
            "decision": "NO CANDIDATE ADVANCES",
            "candidate": None,
            "reason": "No screened pair clears both detector-margin and safety requirements.",
        }
    summary = plain(
        {
            "purpose": "development mechanics/detector co-design; not confirmatory",
            "point_count": args.point_count,
            "simulation_timestep_s": args.simulation_timestep_s,
            "detector_summary_path": str(args.detector_summary),
            "detector_contract": detector,
            "minimum_required_margin": args.minimum_detector_margin,
            "results": results,
            "recommendation": recommendation,
        }
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    write_csv(args.output_dir / "candidate_comparison.csv", results)
    write_report(args.output_dir / "synchronous_safe_probe_report.md", summary)
    print(f"Decision: {recommendation['decision']}; outputs: {args.output_dir}", flush=True)
    return summary


def main() -> int:
    """Run the CLI sensitivity."""

    run(parse_args())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
